# Generated by Django 3.2.6 on 2021-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=30)),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('books', models.CharField(max_length=50)),
            ],
        ),
    ]
